#!/usr/bin/python
import readrouters
import socket

def change(test, end1, end2, newcost):
    routerInfo = readrouters.readrouters(test)

    end1info = (routerInfo[end1].host, routerInfo[end1].baseport)
    end2info = (routerInfo[end2].host, routerInfo[end2].baseport)

    msg1 = 'L %s %d' % (end2, newcost)
    msg2 = 'L %s %d' % (end1, newcost)
    s1 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s2 = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

    s1.connect(end1info)
    s1.send(msg1)
    s1.close()

    s2.connect(end2info)
    s2.send(msg2)
    s2.close()

if __name__=='__main__':
    import sys
    change(sys.argv[1], sys.argv[2], sys.argv[3], int(sys.argv[4])) 
